// module-settings-manager/src/index.tsx
import { render } from "solid-js/web";
import type { ModuleSettingsDoc } from "@inkandswitch/patchwork-filesystem";
import { type ToolImplementation } from "@inkandswitch/patchwork-plugins";

export const plugins = [
  {
    type: "patchwork:datatype",
    id: "patchwork:module-settings",
    name: "Module Settings",
    icon: "Settings",
    unlisted: true,
    async load() {
      const { ModuleSettingsDatatype } = await import("./datatype");
      return ModuleSettingsDatatype;
    },
  },
  {
    id: "module-settings-manager",
    type: "patchwork:tool",
    name: "Module Settings Manager",
    icon: "Settings",
    supportedDatatypes: ["patchwork:module-settings", "my-tools"],
    async load(): Promise<ToolImplementation<ModuleSettingsDoc>> {
      const { ModuleSettings } = await import(
        "./module-settings/module-settings.tsx"
      );
      return function (handle, element) {
        return render(
          () => (
            <ModuleSettings
              handle={handle}
              repo={element.repo}
              element={element as any}
            />
          ),
          element
        );
      };
    },
  },
];

// tldraw4/src/main.tsx
import { createRoot } from "react-dom/client";
import type { ToolImplementation } from "@inkandswitch/patchwork-plugins";
import { datatype as datatype } from "./datatype.ts";
import { RepoContext } from "@automerge/react";
import "./main.css";

function addStyles(textContent: string, element: HTMLElement = document.head) {
  const id = "tldraw4-styles";
  const el = element.querySelector(`#${id}`) ?? document.createElement("style");
  Object.assign(el, { textContent, id });
  element.append(el);
}

async function loadStyles() {
  const url = new URL("./main.css", import.meta.url);
  return (await fetch(url)).text();
}

export const plugins = [
  {
    type: "patchwork:datatype",
    id: "tldraw4",
    name: "Canvas",
    icon: "PenLine",
    async load() {
      return datatype;
    },
  },
  {
    type: "patchwork:tool",
    id: "tldraw4",
    name: "Canvas",
    supportedDatatypes: ["tldraw4"],
    async load(): Promise<ToolImplementation> {
      const { TldrawTool } = await import("./tool.tsx");
      const styles = await loadStyles();
      return (handle, element) => {
        const root = createRoot(element);
        addStyles(styles);
        root.render(
          <RepoContext.Provider value={element.repo}>
            <TldrawTool docUrl={handle.url} />
          </RepoContext.Provider>
        );
        return () => root.unmount();
      };
    },
  },
];
